language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25

before_install:
  - echo "y" | android update sdk -a --no-ui --filter android-21
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-21
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
